version: '3.7'

services:
  scripts:
    image: mjhale/blaseball-reference-scripts:v1.0
    restart: always
    volumes:
      - /srv/docker/blaseballreference/aws/credentials:/root/.aws/credentials:ro
      - /srv/docker/blaseballreference/ssh/id_ed25519:/root/.ssh/id_ed25519:ro
    networks:
      - br_local
    secrets:
      - ssh_key
      - aws_credentials

  minio:
    image: minio/minio
    restart: always
    volumes:
      - /srv/docker/blaseballreference/files:/data
    networks:
      - br_local
    expose:
      - '9000'
    environment:
      MINIO_ROOT_USER: 'ACCESS_KEY_ID'
      MINIO_ROOT_PASSWORD: 'SECRET_ACCESS_KEY'
    command: server /data
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:9000/minio/health/live']
      interval: 30s
      timeout: 20s
      retries: 3

  minio-client:
    image: minio/mc
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host rm local;
      /usr/bin/mc config host add --quiet --api s3v4 local http://minio:9000 ACCESS_KEY_ID SECRET_ACCESS_KEY;
      /usr/bin/mc mb --quiet --ignore-existing local/br-public/;
      /usr/bin/mc policy set download local/br-public;
      "
    depends_on:
      - minio
    networks:
      - br_local

  nginx:
    image: nginx:1.19-alpine
    restart: always
    volumes:
      - /srv/docker/blaseballreference/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
    networks:
      - br_local
      - proxy
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.blaseballreference.entrypoints=https'
      - 'traefik.http.routers.blaseballreference.rule=Host(`files.blaseball-reference.com`)'
      - 'traefik.http.routers.blaseballreference.tls=true'
      - 'traefik.http.routers.blaseballreference.tls.certresolver=sibrResolver'
      - 'traefik.http.services.blaseballreference.loadbalancer.server.port=9000'

networks:
  proxy:
    external:
      name: proxy
  br_local:

secrets:
  ssh_key:
    file: /srv/docker/blaseballreference/ssh/id_ed25519
  aws_credentials:
    file: /srv/docker/blaseballreference/aws/credentials
